set -g mode-keys vi
set -g default-terminal "screen-256color"
set -g extended-keys on
set -g extended-keys-format csi-u


bind Enter copy-mode


bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

